server:
  port: 8018
  undertow:
    threads:
      io: 8
      worker: 256
    buffer-size: 1024
    direct-buffers: true
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @envFlag@
